### ISSUE TITLE
Falta blanquear los campos de nombre y apellido cuando el usuario ingresa un valor incorrecto

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-heredia-erazo#8]
https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L64-L69

**Comment by ivanjalid1** [comment]
la función validarCampo, blanquea los campos
