### ISSUE TITLE
Si una variable no será sobre-escrita debe ser declarada como const

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-heredia-erazo#9]
https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L56-L60

https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L100

https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L140-L141

https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L164

https://github.com/UCC-LabCompu2/proyecto2024-heredia-erazo/blob/21b5cb894912495a28e8a8f9d035a641c6eaebc6/scripts.js#L183

**Comment by ivanjalid1** [comment]
complete
